export type AllBackgroundTraits = 
  | "Blue Pink Clouds"
  | "Blue White Bokeh"
  | "Orange White Bokeh"
  | "Pink White Bokeh"
  | "Plain Blue"
  | "Plain Green"
  | "Plain Pink"
  | "Plain Purple"
  | "Plain Yellow"
  | "Purple Pink Bokeh";

export type AllCupTraits = 
  | "Invisible"
  | "Opaque White"
  | "White";

export type AllDrinkTraits = 
  | "Gradient Blue-Pink"
  | "Solid Aqua"
  | "Solid Beige Cream"
  | "Solid Blue Green"
  | "Solid Blue"
  | "Solid Gray Blue"
  | "Solid Gray Green"
  | "Solid Green Blue"
  | "Solid Green"
  | "Solid Lavender"
  | "Solid Medium Green"
  | "Solid Medium Purple"
  | "Solid Orange"
  | "Solid Periwinkle"
  | "Solid Pink"
  | "Solid Purple"
  | "Solid Red"
  | "Solid Wine"
  | "Solid Yellow Green";

export type AllBlushTraits = 
  | "Blue Spiral"
  | "Blue Star"
  | "Dark Pink Circle"
  | "Dark Pink Heart"
  | "Dark Pink Line"
  | "Dark Pink Oval"
  | "Dark Pink Spiral"
  | "Gray Circle"
  | "Light Pink Circle"
  | "Light Pink Heart"
  | "Light Pink Oval"
  | "Light Pink Spiral"
  | "None"
  | "Orange Circle"
  | "Orange Heart"
  | "Orange Oval"
  | "Orange Spiral"
  | "Pink Circle"
  | "Pink Line"
  | "Pink Star"
  | "Pink Transparent Circle"
  | "Purple Heart"
  | "Purple Spiral"
  | "Purple Star"
  | "Purple Transparent Circle"
  | "Red Circle"
  | "Red Heart"
  | "Red Line"
  | "Red Oval"
  | "Red Spiral"
  | "Red Transparent Circle"
  | "Yellow Star";

export type AllStrawTraits = 
  | "Blue"
  | "Fuchsia"
  | "Green"
  | "None"
  | "Orange"
  | "Purple"
  | "Rainbow"
  | "Red Orange"
  | "Red"
  | "White"
  | "Yellow";

export type AllLidTraits = 
  | "Hamster-Brown"
  | "Hamster-Gray"
  | "Hamster-Orange"
  | "Mouse-Gray"
  | "Mouse-White"
  | "Bear-Black Teddy"
  | "Bear-Brown"
  | "Bear-Dark Brown Teddy"
  | "Bear-Golden Brown Teddy"
  | "Bear-Polar"
  | "Bear-Purple"
  | "Bear-Red Velvet Teddy"
  | "Bear-Yellow"
  | "Bunny-Brown"
  | "Bunny-White"
  | "Cat-Black Spots"
  | "Cat-Brown"
  | "Cat-Orange Spots"
  | "Cat-White"
  | "Cupcake-Blue Sprinkles"
  | "Cupcake-Orange"
  | "Cupcake-Pink Sprinkles"
  | "Cupcake-Pink"
  | "Cupcake-Purple Sprinkles"
  | "Cupcake-Rainbow"
  | "Gorilla-Blue Gray"
  | "Gorilla-Gray"
  | "Ice Cream-Chocolate"
  | "Ice Cream-Strawberry"
  | "Ice Cream-Vanilla"
  | "Monkey-Brown and Pink"
  | "Monkey-Brown"
  | "Nigiri-Light Pink"
  | "Nigiri-Red Orange"
  | "Onigiri-Black and White"
  | "Onigiri-Flavored"
  | "Panda-Black and White"
  | "Panda-Blue"
  | "Panda-Pink"
  | "Panda-Purple"
  | "Pig-Gray"
  | "Pig-Pink"
  | "Poodle-Brown"
  | "Poodle-White"
  | "Shiba-Black"
  | "Shiba-Red";

export type AllEyesTraits = 
  | "Closed U"
  | "Closed V"
  | "Oval Highlighted"
  | "Oval Single Lash"
  | "Oval"
  | "Pie"
  | "Pink Heart Polka Dot"
  | "Pink Heart"
  | "Red Heart"
  | "Relaxed"
  | "Round Bottom Lash"
  | "Round Double Lash"
  | "Round Highlighted"
  | "Round Single Lash"
  | "Round Top Lash Wink"
  | "Round Top Lash"
  | "Round Wink"
  | "Sparkly Bottom Lash"
  | "Sparkly Double Lash Wink"
  | "Sparkly Double Lash"
  | "Sparkly Single Lash"
  | "Sparkly Top Lash"
  | "Sparkly Wink"
  | "Sparkly"
  | "Spiral";

export type AllBobaTraits = 
  | "All Hearts"
  | "Half Cup Round Boba"
  | "Hearts Partial"
  | "Hearts and Stars Partial"
  | "Hearts and Stars"
  | "None"
  | "Shaken Boba"
  | "Stars Partial"
  | "Third Cup Round Black"
  | "Three Rows Boba";

export type AllGlassesTraits = 
  | "Blue Clear"
  | "Gold Round Eyeglasses"
  | "Gray Round Sunglasses"
  | "Green Flower Sunglasses"
  | "Green Round Sunglasses"
  | "Monocle"
  | "None"
  | "Orange Flower Sunglasses"
  | "Orange Round Sunglasses"
  | "Pink Heart Sunglasses"
  | "Purple Gradient Heart Sunglasses"
  | "Purple Round Sunglasses"
  | "Silver Round Eyeglasses"
  | "Solana Heart Sunglasses"
  | "Yellow Round Sunglasses";

export type AllAccessoryTraits = 
  | "Bee"
  | "Blue Bow"
  | "Butterfly"
  | "Candy"
  | "Cherry Blossom"
  | "Clover"
  | "Crown Jewel"
  | "Crown"
  | "Daisy"
  | "Dango"
  | "Double Bows"
  | "Double Red Cherry"
  | "Enchanted Golden Apple"
  | "Flower Stem"
  | "Golden Apple"
  | "Green Apple"
  | "Heart Antenna"
  | "Leaf"
  | "None"
  | "Pink Bow"
  | "Pink Cherry Double"
  | "Pink Cherry"
  | "Pink Rose Head"
  | "Pink Strawberry"
  | "Plain Antenna"
  | "Plant Stem"
  | "Pom Poms"
  | "Purple Bow"
  | "Red Apple"
  | "Red Bow"
  | "Red Cherry"
  | "Red Rose Head"
  | "Red Rose"
  | "Red Strawberry"
  | "Snail"
  | "Sparkles"
  | "Star Antenna"
  | "White Bow"
  | "Yellow Rose Head";

export type AllStickerTraits = 
  | "BTC"
  | "Bandaid"
  | "Boba Cup"
  | "Cactus"
  | "Cake"
  | "Coffee"
  | "Diamond"
  | "Doge"
  | "Flower"
  | "Frog"
  | "Hamburger"
  | "Heart Forehead Sticker"
  | "Ice Cream Cone"
  | "Mushroom"
  | "Music Note"
  | "None"
  | "Pink Heart"
  | "Pizza"
  | "Pumpkin"
  | "Rainbow"
  | "Red Heart"
  | "Rocket"
  | "Shaka"
  | "Solana"
  | "Star Forehead Sticker"
  | "Star"
  | "Tea"
  | "Unicorn"
  | "Waves"
  | "Whale"
  | "gm"
  | "gn"
  | "ily";
